### ISSUE TITLE
Update node16 to node20 to solve workflow issue

### ISSUE THREAD

**Issue by vshah11** [graticule-life/reusable-workflow#10]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: docker/setup-buildx-action@v2

- Potentially updating the docker/setup-buildx-action to version @v3/@v4 should fix the issue. 
- https://github.com/actions/setup-node/issues/850
- https://github.com/actions/setup-dotnet/issues/503

**Comment by adriaanbalt** [comment]
I'm using the generated Firebase YAML file for Hosting.  It looks like this:
```
name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd packages/website && yarn && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOVIEMOOD_6C59F }}'
          channelId: live
          projectId: coolprojectname
```

the default uses ` actions/checkout@v3` but I've changed it to ` actions/checkout@v4`.  I'm still getting this error in Github workflow actions:

[build_and_deploy](https://github.com/adriaanbalt/GREATFLIX/actions/runs/8308530068/job/22738866328)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: FirebaseExtended/action-hosting-deploy@v0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

I'm not using Docker so I'm not sure if I need to use `docker/setup-buildx-action@v2`
